CREATE DATABASE IF NOT EXISTS history_hunt_ph;
USE history_hunt_ph;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(18) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  game_name VARCHAR(20) DEFAULT NULL,
  gender VARCHAR(32) DEFAULT NULL,
  avatar LONGTEXT DEFAULT NULL,
  score INT NOT NULL DEFAULT 0,
  coins INT NOT NULL DEFAULT 0,
  solved INT NOT NULL DEFAULT 0,
  streak INT NOT NULL DEFAULT 0,
  best_score INT NOT NULL DEFAULT 0,
  best_solved INT NOT NULL DEFAULT 0,
  best_streak INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_username (username)
);
